set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B_IBUF[0]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B_IBUF[1]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B_IBUF[2]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B_IBUF[3]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B_IBUF[4]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B_IBUF[5]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B_IBUF[6]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B_IBUF[7]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B_IBUF[8]]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B[0]_IBUF]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B[1]_IBUF]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B[2]_IBUF]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B[3]_IBUF]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B[4]_IBUF]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B[5]_IBUF]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B[6]_IBUF]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B[7]_IBUF]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets B[8]_IBUF]


set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN W7 [get_ports segments[0]]
set_property IOSTANDARD LVCMOS33 [get_ports segments[0]]
set_property PACKAGE_PIN W6 [get_ports segments[1]]
set_property IOSTANDARD LVCMOS33 [get_ports segments[1]]
set_property PACKAGE_PIN U8 [get_ports segments[2]]
set_property IOSTANDARD LVCMOS33 [get_ports segments[2]]
set_property PACKAGE_PIN V8 [get_ports segments[3]]
set_property IOSTANDARD LVCMOS33 [get_ports segments[3]]
set_property PACKAGE_PIN U5 [get_ports segments[4]]
set_property IOSTANDARD LVCMOS33 [get_ports segments[4]]
set_property PACKAGE_PIN V5 [get_ports segments[5]]
set_property IOSTANDARD LVCMOS33 [get_ports segments[5]]
set_property PACKAGE_PIN U7 [get_ports segments[6]]
set_property IOSTANDARD LVCMOS33 [get_ports segments[6]]
set_property PACKAGE_PIN V7 [get_ports dot]
set_property IOSTANDARD LVCMOS33 [get_ports dot]

set_property PACKAGE_PIN W4 [get_ports enabler[3]]
set_property IOSTANDARD LVCMOS33 [get_ports enabler[3]]
set_property PACKAGE_PIN V4 [get_ports enabler[2]]
set_property IOSTANDARD LVCMOS33 [get_ports enabler[2]]
set_property PACKAGE_PIN U4 [get_ports enabler[1]]
set_property IOSTANDARD LVCMOS33 [get_ports enabler[1]]
set_property PACKAGE_PIN U2 [get_ports enabler[0]]
set_property IOSTANDARD LVCMOS33 [get_ports enabler[0]]

set_property PACKAGE_PIN R2 [get_ports B[0]]
set_property IOSTANDARD LVCMOS33 [get_ports B[0]]
set_property PACKAGE_PIN T1 [get_ports B[1]]
set_property IOSTANDARD LVCMOS33 [get_ports B[1]]
set_property PACKAGE_PIN U1 [get_ports B[2]]
set_property IOSTANDARD LVCMOS33 [get_ports B[2]]
set_property PACKAGE_PIN W2 [get_ports B[3]]
set_property IOSTANDARD LVCMOS33 [get_ports B[3]]

set_property PACKAGE_PIN R3 [get_ports B[4]]
set_property IOSTANDARD LVCMOS33 [get_ports B[4]]
set_property PACKAGE_PIN T2 [get_ports B[5]]
set_property IOSTANDARD LVCMOS33 [get_ports B[5]]
set_property PACKAGE_PIN T3 [get_ports B[6]]
set_property IOSTANDARD LVCMOS33 [get_ports B[6]]
set_property PACKAGE_PIN V2 [get_ports B[7]]
set_property IOSTANDARD LVCMOS33 [get_ports B[7]]
set_property PACKAGE_PIN W13 [get_ports B[8]]
set_property IOSTANDARD LVCMOS33 [get_ports B[8]]
